---
name: CI
on:   # yamllint disable-line rule:truthy
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - ci-test

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: CRLF endings
              uses: erclu/check-crlf@v1

            - name: Find trailing whitespace
              uses: harupy/find-trailing-whitespace@v1.0

            - name: Validate YAML files
              run: yamllint .

            - name: Ruff
              uses: chartboost/ruff-action@v1
              with:
                  src: eadk_discord

            - name: Mypy
              uses: jashparekh/mypy-action@v2
              with:
                  mypy_version: 1.11.2
                  requirement_files: requirements.txt requirements_dev.txt
                  python_version: '3.12'
