---
name: CI
on:   # yamllint disable-line rule:truthy
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - ci-test

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: CRLF endings
              uses: erclu/check-crlf@v1

            - name: Find trailing whitespace
              uses: harupy/find-trailing-whitespace@v1.0

            - name: Validate YAML files
              run: yamllint . --strict

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: 0.4.18

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: pyproject.toml

            - name: Install the project
              run: uv sync --all-extras --dev

            - name: Ruff
              run: uv run ruff check

            - name: Mypy
              run: uv run mypy .

            - name: Run pytest
              run: uv run pytest --cov --cov-report=term-missing
